package com.java.common;

public enum PageType {
	HOME_PAGE,
	PRODUCT_PAGE,
	CART_PAGE,
	ORDER_PAGE,
	DETAIL_ORDER_PAGE,
	DETAIL_PRODUCT_PAGE,
	SEARCH_PAGE,
	HELP_PAGE,
	ADMIN_HOME_PAGE,
	ADMIN_ORDER_PAGE,
	ADMIN_USER_PAGE,
	ADMIN_USER_FORM_PAGE,
	ADMIN_USER_UPDATE_PAGE,
	ADMIN_PRODUCT_PAGE,
	ADMIN_DISCOUNT_PAGE,
	ADMIN_SUPPORT_PAGE,
	ADMIN_DISCOUNT_FORM_PAGE,
	ADMIN_DISCOUNT_UPDATE_PAGE,
	ADMIN_PRODUCT_FORM_PAGE,
	ADMIN_PRODUCT_UPDATE_PAGE
}
